parallel execution with tp=1

diff --git a/infer/vllm/runner b/infer/vllm/runner
--- a/infer/vllm/runner
+++ b/infer/vllm/runner
@@ -7,21 +7,21 @@ while [ -L "$SOURCE" ]; do
     [[ $SOURCE != /* ]] && SOURCE=$SDIR/$SOURCE; done
 SDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
 
-#if [[ ${#} -lt 19 ]]; then
-#    if [[ "${1}" != "-h" && ${1} != "--help" ]]; then
-#        echo "error: missing arguments"
-#    fi
-#
-#    echo "  rdir:   root output directory"
-#    echo "  mr:     model root directory"
-#    echo "  mmtps:  model names and associated tps"
-#    echo "  iis:    input sizes  + mode (split|batch|single)"
-#    echo "  oos:    output sizes + mode (split|batch|single)"
-#    echo "  bbs:    batch sizes  + mode (split|batch|single)"
-#    echo "  devs:   devsets (or 'auto')"
-#    echo "  sdir:   suffix directory"
-#    exit 1
-#fi
+if [[ ${#} -lt 19 ]]; then
+    if [[ "${1}" != "-h" && ${1} != "--help" ]]; then
+        echo "error: missing arguments"
+    fi
+
+    echo "  rdir:   root output directory"
+    echo "  mr:     model root directory"
+    echo "  mmtps:  model names and associated tps"
+    echo "  iis:    input sizes  + mode (split|single)"
+    echo "  oos:    output sizes + mode (split|single)"
+    echo "  bbs:    batch sizes  + mode (split|single)"
+    echo "  devs:   devsets (or 'auto')"
+    echo "  sdir:   suffix directory"
+    exit 1
+fi
 
 shift;  rdir=${1}; shift
 shift;    mr=${1}; shift
@@ -59,17 +59,22 @@ echo "sdir = ${sdir}"               |& tee -a ${bdir}/params
 echo "@    = ${@}"                  |& tee -a ${bdir}/params
 echo
 
-#if [[ ${devs} == auto ]]; then
-#    tp_1="0:1:2:3:4:5:6:7"
+# Read PCIe address of devices
+#cp /tmp/etc/aiu/senlib_config-autogen.json /etc/aiu/senlib_config.json
+read -a device <<< "$(/opt/sentient/bin/aiu-query-devices | grep "AIU"| tail -n 16 |awk '{print $4}' |tr -s \\n " " | sed 's/ *$//')"
+#for i in ${device[@]}; do echo $i; done
+
+if [[ ${devs} == auto ]]; then
+    tp_1="0:1:2:3:4:5:6:7:8:9:10:11:12:13:14:15"
 #    tp_2="0,1:2,3:4,5:6,7"
 #    tp_4="0,1,2,3:4,5,6,7"
 #    tp_8="0,1,2,3,4,5,6,7"
-#else
-#    tp_1=$(echo ${devs} | cut -d / -f 1)
+else
+     tp_1=$(echo ${devs} | cut -d / -f 1)
 #    tp_2=$(echo ${devs} | cut -d / -f 2)
 #    tp_4=$(echo ${devs} | cut -d / -f 3)
 #    tp_8=$(echo ${devs} | cut -d / -f 4)
-#fi
+fi
 
 for mmtp in ${mmtps//,/ } ; do
 for ii   in ${iis_for}    ; do
@@ -79,8 +84,9 @@ for bb   in ${bbs_for}    ; do
 mm=$(echo ${mmtp} | cut -d ':' -f 1)
 tp=$(echo ${mmtp} | cut -d ':' -f 2)
 
-#devsets=$(eval echo \${tp_${tp}})
-#if [[ -z "${devsets}" ]]; then continue; fi
+devsets=$(eval echo \${tp_${tp}})
+echo ${devsets}
+if [[ -z "${devsets}" ]]; then continue; fi
 
 etim="$(date +%Y%m%d-%H%M%S.%N)"
 edir="${bdir}/${etim}"
@@ -93,46 +99,46 @@ edir+="/${sdir}"
 
 mkdir -p ${edir}/utils
 
-#LOCK=lock-$(hostname)-dev
-#
-#function lock {
-#    local devsets=${1}; shift
-#
-#    while :; do
-#
-#        for devset in ${devsets//:/ }; do
-#            locked=""
-#
-#            for dev in ${devset//,/ }; do
-#                mkdir ${LOCK}.${dev} &> /dev/null
-#
-#                if [[ ${?} -eq 0 ]];
-#                    then locked+="${dev} "
-#                else
-#                    for dev in ${locked}; do
-#                        rmdir ${LOCK}.${dev} &> /dev/null
-#                    done
-#                    continue 2
-#                fi
-#            done
-#            break 2 # devset found
-#        sleep 1
-#        done # try next devset
-#    sleep 2
-#    done # try next loop
-#
-#    echo ${devset}
-#}
-#
-#function unlock {
-#    local devset=${1}; shift
-#
-#    for dev in ${devset//,/ }; do
-#        rmdir ${LOCK}.${dev}
-#    done
-#}
-#
-#devset=$(lock ${devsets})
+LOCK=lock-$(hostname)-dev
+
+function lock {
+    local devsets=${1}; shift
+
+    while :; do
+
+        for devset in ${devsets//:/ }; do
+            locked=""
+
+            for dev in ${devset//,/ }; do
+                mkdir ${LOCK}.${dev} &> /dev/null
+
+                if [[ ${?} -eq 0 ]];
+                    then locked+="${dev} "
+                else
+                    for dev in ${locked}; do
+                        rmdir ${LOCK}.${dev} &> /dev/null
+                    done
+                    continue 2
+                fi
+            done
+            break 2 # devset found
+        sleep 1
+        done # try next devset
+    sleep 2
+    done # try next loop
+
+    echo ${devset}
+}
+
+function unlock {
+    local devset=${1}; shift
+
+    for dev in ${devset//,/ }; do
+        rmdir ${LOCK}.${dev}
+    done
+}
+
+devset=$(lock ${devsets})
 
 if [[ ${iis_mode} == "split" ]]; then iis_driver=${ii}; else iis_driver=${iis}; fi
 if [[ ${oos_mode} == "split" ]]; then oos_driver=${oo}; else oos_driver=${oos}; fi
@@ -148,23 +154,28 @@ ${SDIR}/driver
     -t   ${tp}
     ${@}
 "
+declare -a port=(12355 12356)
 
 function run {
     #export PYTHONUNBUFFERED=1
-    #export CUDA_DEVICE_ORDER=PCI_BUS_ID
-    #export CUDA_VISIBLE_DEVICES=${devset}
+    export AIU_WORLD_RANK_0=${device[devset]}
+    export FLEX_RDMA_PCI_BUS_ADDR_0=${device[devset]}
+    export MASTER_PORT=${port[devset]}
+    echo "AIU_WORLD_RANK_0=${AIU_WORLD_RANK_0}"
+    echo "FLEX_RDMA_PCI_BUS_ADDR_0=${FLEX_RDMA_PCI_BUS_ADDR_0}"
+    echo "MASTER_PORT=${MASTER_PORT}"
     env         &> ${edir}/utils/env
     pip list    &> ${edir}/utils/pip-list
     echo ${cmd}  > ${edir}/exp.cmd
     eval ${cmd} &> ${edir}/exp.log
-    sleep 400
+    sleep 300
     out=$(ps auxww | grep -v grep | grep driver | grep ${btim}/${etim})
     if [[ ${?} -eq 0 ]]; then
         echo "${out}" | tr -s ' ' | cut -d ' ' -f 2 | xargs kill -2
         sleep 5
     fi
     sleep 30
-    #unlock ${devset}
+    unlock ${devset}
 
     echo -e "\e[95m$(printf "%-15s" ${devset}) \e[102mDONE\e[0m \e[93m${edir}\e[0m"
 }
@@ -182,3 +193,4 @@ wait
 echo
 echo ${bdir}
 echo
+
